<?php
$title = ucfirst($this->album->getTitle());
$description = ucfirst($this->album->getDescription());
$medias = $this->albumContent($this->album, $this->page);
$paginationControl = $this->paginationControl($medias);
$editable = $this->album->isEditableBy($this->user, $this->acl);
$editLink = $editable ? $this->editLink($this->album) : '';
$commentsAllowed = !in_array($this->album->id, array(
	Media_Album_PhotoMain::ID,
	Media_Album_VideoMain::ID,
	Media_Album_Portfolio::ID)); 
$commentClass = $commentsAllowed ? ' withComments' : '';
$displayDescription = '';
if($description != $title && !empty($description)){
	$displayDescription = '<span class="headerCardAction">&nbsp;- '.ucfirst($description).'</span>'.PHP_EOL;
}

$hc = new HeaderContent($title.$displayDescription);
$hc->setHeaderActions('<span class="headerCardAction headerCardActionInMenu">'.$editLink.'</span>');
$hc->setSubHeaderActions(
    renderPaginationControl($paginationControl, 'top headerCardAction headerCardActionInMenu'),
    renderActions($this->album, $this->user, $this)
);

function renderTitle($title, $displayDescription, $editLink)
{
	$titleTemplate = '<h1 id="mainTitle" class="albumTitle">%s%s%s</h1>';
	return sprintf($titleTemplate, $title, $displayDescription, $editLink).PHP_EOL;
}

function renderPaginationControl($paginationControl, $extraClasses)
{
	if (empty($paginationControl)) {
		return '';
	}
		
	$ret = "<div class=\"albumPagination paginationControl $extraClasses\">".PHP_EOL;
	$ret .= '	'.$paginationControl.PHP_EOL;
	$ret .='</div>'.PHP_EOL;
	return $ret;
}

function renderActions($album, $user, $view)
{
	$ret = '';
	switch($album->id){
		case Media_Album_PhotoMain::ID:
			$prepend = '<div class="addPhotoContainer">'.PHP_EOL.'	<div class="addPhoto actionLinkContainer">'.PHP_EOL;
			$append = '	</div>'.PHP_EOL.'</div>'.PHP_EOL;
			$ret .= $view->actionLink(
					$prepend,
					$append,
					$user,
					array(
						'route' => 'uploadphotomain',
						'title' => null,
						'params' => array()
					),
					'dataLink photo');
			break;
		case Media_Album_VideoMain::ID:
			$prepend = '<div class="addVideo actionLinkContainer">'.PHP_EOL;
			$append = '</div>'.PHP_EOL;
			$ret .= $view->actionLink(
					$prepend,
					$append,
					$user,
					array(
						'route' => 'uploadvideo',
						'title' => null,
						'params' => array()
					), 'dataLink video');
			break;
		case Media_Album_Portfolio::ID:
			if($view->acl->isAllowed($user, Lib_Acl::EDITOR_RESOURCE)){
				$ret .= '<div class="addPhoto actionLinkContainer">'.PHP_EOL;
				$ret .= '	'.$view->routeLink('uploadportfolio').PHP_EOL;
				$ret .= '</div>'.PHP_EOL;
			}
			break;
		default:
			if($album->albumCreation == Media_Album::CREATION_AUTOMATIC) {
				$parent = $album->getParent();
				if(!empty($parent)){
					if($parent instanceof User_Row){
						$ret .= 'back to the profile of '.$view->userLink($parent).PHP_EOL;
					} else {
						$ret .= 'back to the page of ' .$view->itemLink($parent).PHP_EOL;
					}
				}
			} else {
				$ret .= "<p>". $view->renderDataInformation($album) ."</p>";
			}
			break;
	}
	return $ret;
}

function renderAlbum($medias, $view)
{
	$ret = '<ul class="albumList">'.PHP_EOL;
	foreach($medias as $media){
		$typeClass = $media['mediaType'] == Media_Item::TYPE_VIDEO ? 'video' : 'photo';
		$ret .= "<li class=\"media $typeClass\">".PHP_EOL;
		$ret .= $view->mediaThumbnail($media, null, null, true);		
		$ret .= '</li>'.PHP_EOL;
	}
	$ret .= '</ul>'.PHP_EOL;
	return $ret;
}

$this->headTitle($title);

echo $this->cardHeader($hc).PHP_EOL;

echo '<div class="card albumCard">'.PHP_EOL;
	echo renderAlbum($medias, $this).PHP_EOL;
echo '</div>'.PHP_EOL;

if ($paginationControl) {
	echo '<div class="listNavigation card">'.PHP_EOL;
	echo renderPaginationControl($paginationControl, 'bottom'.$commentClass).PHP_EOL;
	echo '</div>'.PHP_EOL;
}

if ($commentsAllowed) {
	echo '<div class="card">'.PHP_EOL;
		echo $this->renderComments($this->comments, $this->album, $this->lastLogin);
	echo '</div>'.PHP_EOL;
}