<?php
$this->headTitle(ucfirst($this->media->getTitle()));
$tags = $this->keywords = $this->media->getTags();
$editable = $this->media->isEditableBy($this->user, $this->acl);
$description = $this->media->getDescription();
$backToAlbum = sprintf($this->translate('backToAlbum'), $this->album->getTitle());
$renderer = $this->mediaDisplay();

if($this->media->mediaType == Media_Item::TYPE_PHOTO){
	$inMedia = 'ridersInPhoto';
    $prev = 'prevPhoto';
    $next = 'nextPhoto';
} else {
	$inMedia = 'ridersInVideo';
    $prev = 'prevVideo';
    $next = 'nextVideo';
}

if(!empty($this->previousMedia)){
	$this->headLink()->headLink(array(
		'rel' => 'prev',
		'href' => $this->previousMedia->getLink()
	));
}

if(!empty($this->nextMedia)){
	$this->headLink()->headLink(array(
		'rel' => 'next',
		'href' => $this->nextMedia->getLink()
	));
}
echo '	<div><div id="backToAlbum" class="actionLinkContainer">'.$this->itemLink(array('name'=>$backToAlbum, 'link'=>$this->album->getLink(), 'itemType' => Constants_DataTypes::MEDIAALBUM), 'dataLink album').'</div></div>'.PHP_EOL;

if(!empty($this->previousMedia) || !empty($this->nextMedia)){
	echo '	<div id="mediaNavigation">'.PHP_EOL;
	if(!empty($this->previousMedia)){
		$link = $this->previousMedia->getLink();
		$img = '/'.$this->baseUrl . IMAGES_PATH . 'left.png';
		echo '		<div class="actionLinkContainer prevMedia">'.$this->itemLink($this->previousMedia, 'linkLeft', 'prev').'</div>'.PHP_EOL;
	}
	if(!empty($this->nextMedia)){
		$link = $this->nextMedia->getLink();
		$img = '/'.$this->baseUrl . IMAGES_PATH . 'right.png';
		echo '		<div class="actionLinkContainer nextMedia">'.$this->itemLink($this->nextMedia, 'linkRight', 'next').'</div>'.PHP_EOL;
	}
	echo '	</div>'.PHP_EOL;
}

?>
<div class="mediaTitle"><?php
echo '<h1 id="mainTitle">'.ucfirst($this->media->getTitle()).'</h1>';
if($editable){
	echo $this->itemStatus($this->media);
	echo $this->editLink($this->media);
	echo $this->deleteLink($this->media);
}
echo $this->renderMediaInformation($this->media);

if($this->media->mediaType == Media_Item::TYPE_PHOTO && $editable){
	echo $this->mediaPhotoRotateLinks($this->media).PHP_EOL;
}

?>
</div>
<?php

if($this->media->mediaType == Media_Item::TYPE_PHOTO){
	echo '<div class="media photo">'.PHP_EOL;
} else {
	echo '<div class="media video">'.PHP_EOL;
}
echo '<div class="mediaContainer">'.PHP_EOL.$renderer->render($this->media, $editable).'</div>'.PHP_EOL;

echo '<div class="mediaMetadata">'.PHP_EOL;

echo '	<div class="mediaMetadataText mediaMetadataTextHorizontal">'.PHP_EOL;
echo $this->shareButtons()->all(APP_URL.$this->url(), 'horizontal').PHP_EOL;

echo $renderer->alternateLink($this->media);

if(!empty($description)){
	echo '		<div class="mediaDescription">'.$description.'</div>'.PHP_EOL;
}
if(!empty($this->spot) || !empty($this->trick) || !empty($this->riders['byId']) || !empty($this->riders['byName']) || !empty($tags)){
	echo '		<div class="mediaMetadataLinks deemphasized-text">'.PHP_EOL;
}
if(!empty($this->spot) || !empty($this->trick) || !empty($this->riders['byId']) || !empty($this->riders['byName'])){
	echo '		<ul class="">'.PHP_EOL;
	echo '		<li>'.ucfirst($this->translate($inMedia)).':</li>'.PHP_EOL;
	}

if(!empty($this->riders['byId']) || !empty($this->riders['byName'])){
	$linkString = array();
	foreach($this->riders['byId'] as $rider){
		$linkString[] = $this->userLink($rider);
	}
	foreach($this->riders['byName'] as $rider){
		$linkString[] = $rider;
	}
	echo '		<li>' .implode(', ', $linkString) .'</li>'.PHP_EOL;
}
if(!empty($this->trick)){
	echo '		<li>'.$this->itemLink($this->trick).'</li>'.PHP_EOL;
}
if(!empty($this->spot)){
	echo '		<li>'.$this->itemLink($this->spot).'</li>'.PHP_EOL;
}

if(!empty($this->spot) || !empty($this->trick) || !empty($this->riders['byId']) || !empty($this->riders['byName'])){
	echo '		</ul>'.PHP_EOL;
}

echo $this->renderTags($tags);
if(!empty($this->spot) || !empty($this->trick) || !empty($this->riders['byId']) || !empty($this->riders['byName']) || !empty($tags)){
	echo '		</div>'.PHP_EOL;
	}
echo '	</div>'.PHP_EOL;

if($this->media->hasLocation()){
	$mapElementId = 'simpleMapElement';
	$location = $this->media->getLocation();
	$location->zoom = DEFAULT_MEDIA_MAP_ZOOM;
	$this->googleMaps()->displayItem($location, array('mapElementId' => $mapElementId));
	$content = '   <div id="'.$mapElementId.'" style="left:0"><img src="'.$this->staticGoogleMap($location, 288, 288).'" alt="" /></div>'.PHP_EOL;

	echo '	<div class="mediaMetadataMap">'.$content.'</div>'.PHP_EOL;
} else {
	echo '	<div class="mediaMetadataNoMap"></div>'.PHP_EOL;
}
echo '	</div>'.PHP_EOL;
echo '</div>'.PHP_EOL;

echo $this->renderComments($this->comments, $this->media, $this->lastLogin);
