<?php
$backToAlbum = sprintf($this->translate('backToAlbum'), $this->album->getTitle());
if($this->media) {
	if($this->mediaType == Media_Item::TYPE_PHOTO) {
		$string = ucfirst($this->translate('editPhotoTitle'));
	} else {
		$string = ucfirst($this->translate('editVideoTitle'));
	}
} else {
	if($this->mediaType == Media_Item::TYPE_PHOTO) {
		$string = ucfirst($this->translate('uploadPhotoTitle'));
	} else {
		$string = ucfirst($this->translate('uploadVideoTitle'));
	}
}
	
$this->headTitle($string);
?>
<div class="card albumHeader">
	<h1 id="mainTitle" class="albumTitle"><?php echo $string ?></h1>
	<div id="backToAlbum" class="actionLinkContainer uploadPage">
<?php
echo $this->itemLink(array(
	'name'=>$backToAlbum,
	'link'=>$this->album->getLink(),
	'itemType' => Constants_DataTypes::MEDIAALBUM
), 'dataLink album').PHP_EOL;
?>
	</div>
</div>
<?php
if ($this->mediaType == Media_Item::TYPE_PHOTO && !$this->media) {
	echo '<div class="card">'.PHP_EOL;
		echo $this->facebook_UploadLink();
	echo '</div>'.PHP_EOL;
}
?>
<div class="card">
<?php
	echo $this->form;
?>
</div>
