<?php
$title = ucfirst($this->translate(
    getTitleString($this->media, $this->mediaType)));	
$hc = new HeaderContent($title);
$hc->setHeaderActions(null, getBackToAlbum($this->album, $this));
if ($fb = maybeGetFacebookUpload($this->mediaType, $this->media, $this)) {
    $hc->setSubHeaderActions(null, $fb);
}

function getTitleString($media, $mediaType)
{
    if($media) {
    	if($mediaType == Media_Item::TYPE_PHOTO) {
    		return 'editPhotoTitle';
    	} else {
    		return 'editVideoTitle';
    	}
    } else {
    	if($mediaType == Media_Item::TYPE_PHOTO) {
    		return 'uploadPhotoTitle';
    	} else {
    		return 'uploadVideoTitle';
    	}
    }
}

function getBackToAlbum($album, $view)
{
    $backToAlbum = sprintf($view->translate('backToAlbum'), $album->getTitle());
    $ret = '';
    $ret .= '<div id="backToAlbum" class="actionLinkContainer uploadPage '.
        'headerCardAction headerCardActionInMenu">'.PHP_EOL;
    $ret .= $view->itemLink(array(
        'name' => $backToAlbum,
        'link' => $album->getLink(),
        'itemType' => Constants_DataTypes::MEDIAALBUM
    ), 'dataLink album').PHP_EOL;
	$ret .= '</div>'.PHP_EOL;
    return $ret;
}

function maybeGetFacebookUpload($mediaType, $media, $view)
{
    $ret = '';
    if ($mediaType == Media_Item::TYPE_PHOTO && !$media) {
        $ret .= '<div class="headerCardAction headerCardActionInMenu">'.PHP_EOL;
		$ret .= $view->facebook_UploadLink();
		$ret .= '</div>'.PHP_EOL;
    }
    return $ret;
}

$this->headTitle($title);

echo $this->cardHeader($hc).PHP_EOL;
echo '<div class="card">'.PHP_EOL;
echo $this->form.PHP_EOL;
echo '</div>'.PHP_EOL;
