<?php
$backToAlbum = sprintf($this->translate('backToAlbum'), $this->album->getTitle());
if($this->photo){
	$string = ucfirst($this->translate('editPhotoTitle'));
} else {
	$string = ucfirst($this->translate('uploadPhotoTitle'));
}
?>
<h1 id="mainTitle" class="albumTitle"><?php echo $string ?></h1>
<?php
echo $this->facebook_UploadLink();
echo '	<div id="backToAlbum" class="actionLinkContainer uploadPage">'.$this->itemLink(array('name'=>$backToAlbum, 'link'=>$this->album->getLink(), 'itemType' => Constants_DataTypes::MEDIAALBUM), 'dataLink album').'</div>'.PHP_EOL;
$this->headTitle($string);
echo $this->form;
