<?php
$title = ucfirst($this->forum->getTitle());
$paginationControl = $this->paginationControl(
	$this->topics,
	null,
	null,
	array(
		'name' => $this->forum->getCleanTitle(),
		'id' => $this->forum->id
	)
);

$hc = new HeaderContent($title);
$hc->setHeaderActions(
    renderModerators($this->moderators, $this),
    renderJumpForm($this->forumListForm, $this)
);
$hc->setSubHeaderActions(
    renderPaginationControl($paginationControl, 'top headerCardAction headerCardActionInMenu'),
    $this->addNewDataLink($this->dataType, $this->forum->id, true)
);

$this->headTitle($title);

function renderJumpForm($form, $view)
{
	$ret = '<div class="headerCardAction">'.PHP_EOL;
	$ret .= '	<div class="actionLinkContainer" id="forumListMain">'.PHP_EOL;
	$ret .= 		ucfirst($view->translate('goToForum')).' '.$form.PHP_EOL;
	$ret .= '	</div>'.PHP_EOL;
	$ret .= '</div>'.PHP_EOL;
	return $ret;
}

function renderPaginationControl($paginationControl, $extraClasses)
{
	if (empty($paginationControl)) {
		return '';
	}

	$ret = "<div class=\"paginationControl $extraClasses\">".PHP_EOL;
	$ret .= '	'.$paginationControl.PHP_EOL;
	$ret .='</div>'.PHP_EOL;
	return $ret;
}

function renderModerators($moderators, $view)
{
	if(!$moderators) {
		return '';
	}
	$ret = '<div class="moderatorInfo headerCardAction">'.PHP_EOL;
	$ret .= ucfirst($view->translate('forumModeratorsList')).': '.PHP_EOL;
	$ret .='	<ul class="forumModeratorList">'.PHP_EOL;
	foreach($moderators as $moderator){
		$ret .= '		<li>'.$view->userLink($moderator).'</li>'.PHP_EOL;
	}
	$ret .= '	</ul>'.PHP_EOL;
	$ret .= '</div>'.PHP_EOL;
	return $ret;
}

/**
 * RENDERING
 */
echo $this->cardHeader($hc).PHP_EOL;
echo'<div class="card noPaddingCard">'.PHP_EOL;
	echo $this->forumTopicList($this->topics, $this->lastLogin);
echo '</div>'.PHP_EOL;
if ($paginationControl) {
	echo '<div class="listNavigation card">'.PHP_EOL;
		echo renderPaginationControl($paginationControl, 'bottom').PHP_EOL;
	echo '</div>'.PHP_EOL;
}