<?php
$title = ucfirst($this->forum->getTitle());
$paginationControl = $this->paginationControl(
	$this->topics,
	null,
	null,
	array(
		'name' => $this->forum->getCleanTitle(),
		'id' => $this->forum->id
	)
);

function renderTitle($title)
{
	$titleTemplate = '<h1 class="forumTitle">%s</h1>';
	return sprintf($titleTemplate, $title).PHP_EOL;
}

function renderJumpForm($form, $view)
{
	$ret = '<div class="forumHeaderJump">'.PHP_EOL;
	$ret .= '	<div class="actionLinkContainer" id="forumListMain">'.PHP_EOL;
	$ret .= 		ucfirst($view->translate('goToForum')).' '.$form.PHP_EOL;
	$ret .= '	</div>'.PHP_EOL;
	$ret .= '</div>'.PHP_EOL;
	return $ret;
}

function renderPaginationControl($paginationControl, $extraClasses)
{
	if (empty($paginationControl)) {
		return '';
	}

	$ret = "<div class=\"forum paginationControl $extraClasses\">".PHP_EOL;
	$ret .= '	'.$paginationControl.PHP_EOL;
	$ret .='</div>'.PHP_EOL;
	return $ret;
}

function renderModerators($moderators, $view)
{
	if(!$moderators) {
		return '';
	}
	$ret = '<div class="moderatorInfo">'.PHP_EOL;
	$ret .= ucfirst($view->translate('forumModeratorsList')).': '.PHP_EOL;
	$ret .='	<ul class="forumModeratorList">'.PHP_EOL;
	foreach($moderators as $moderator){
		$ret .= '		<li>'.$view->userLink($moderator).'</li>'.PHP_EOL;
	}
	$ret .= '	</ul>'.PHP_EOL;
	$ret .= '</div>'.PHP_EOL;
	return $ret;
}

$this->headTitle($title);

echo '<div class="forumHeader card">'.PHP_EOL;
	echo '<div class="forumHeaderTitle">'.PHP_EOL;
		echo renderTitle($title).PHP_EOL;
		echo renderModerators($this->moderators, $this).PHP_EOL;
	echo '</div>'.PHP_EOL;
	echo renderJumpForm($this->forumListForm, $this).PHP_EOL;
echo '</div>'.PHP_EOL;

echo '<div class="forumNavigation card">'.PHP_EOL;
	echo renderPaginationControl($paginationControl, 'top').PHP_EOL;
	echo $this->addNewDataLink($this->dataType, $this->forum->id);
echo '</div>'.PHP_EOL;
echo'<div class="card">'.PHP_EOL;
	echo $this->forumTopicList($this->topics, $this->lastLogin);
echo '</div>'.PHP_EOL;
	
if ($paginationControl) {
	echo '<div class="forumNavigation card">'.PHP_EOL;
		echo renderPaginationControl($paginationControl, 'bottom').PHP_EOL;
	echo '</div>'.PHP_EOL;
}