<?php
$title = ucfirst($this->translate('forums'));

function renderTitle($title)
{
	$titleTemplate = '<h1 id="mainTitle" class="forumTitle">%s</h1>';
	return sprintf($titleTemplate, ucfirst($title)).PHP_EOL;
}

function renderJumpForm($form, $view)
{
	$ret = '<div class="actionLinkContainer" id="forumListMain">'.PHP_EOL;
	$ret .= '<span class="hiddenOnMobile">'.ucfirst($view->translate('goToForum')).'</span> '.$form.PHP_EOL;
	$ret .= '</div>'.PHP_EOL;
	return $ret;
}

$this->headTitle($title);

echo '<div class="card forumHeader">'.PHP_EOL;
echo renderTitle($title).PHP_EOL;
echo renderJumpForm($this->forumListForm, $this).PHP_EOL;
echo '</div>'.PHP_EOL;

echo $this->forumsList($this->forums, $this->lastLogin).PHP_EOL;
