<?php
$userCanPost = !in_array($this->user->status,
	array(
		User::STATUS_BANNED,
		User::STATUS_GUEST,
		User::STATUS_PENDING		
	)
);
$title = ucfirst($this->topic->getTitle());
$paginationControl = $this->paginationControl(
	$this->posts,
	null,
	null,
	array(
		'name' => $this->topic->getCleanTitle(),
		'id' => $this->topic->id
	)
);
$forum = $this->topic->getForum();
$linkInfo = array(
	'itemType' => $forum->getItemType(),
	'link' => $forum->getLink(),
	'name' => sprintf($this->translate('backToForum'), $forum->getTitle())
);

function renderTitle($title)
{
	$titleTemplate = '<h1 id="mainTitle" class="topicTitle">%s</h1>';
	return sprintf($titleTemplate, $title).PHP_EOL;
}

function renderTopicActions($topic, $user, $view, $acl)
{
    $return = '';
	if($topic->isEditableBy($user, $acl)){
	    $return .= '<div class="headerCardAction headerCardActionInMenu">'.PHP_EOL;
		$return .= $view->itemStatus($topic, true);
		$return .=  $view->editLink($topic);
		if(count($topic->getPosts()) == 1){
			$return .= $view->deleteLink($topic);
		}
		$return .= '</div>'.PHP_EOL;
	}
	return $return;
}

function renderPaginationControl($paginationControl, $extraClasses)
{
	if (empty($paginationControl)) {
		return '';
	}

	$ret = "<div class=\"topic paginationControl $extraClasses\">".PHP_EOL;
	$ret .= '	'.$paginationControl.PHP_EOL;
	$ret .='</div>'.PHP_EOL;
	return $ret;
}

$hc = new HeaderContent($title);
$hc->setTitleClass('forumHeader');
$hc->setHeaderActions(
    renderTopicActions($this->topic, $this->user, $this, $this->acl),
    '<div class="actionLinkContainer backToTopicLink headerCardAction headerCardActionInMenu">'.$this->itemLink($linkInfo).'</div>'
);
$hc->setSubHeaderActions(
    renderPaginationControl($paginationControl, 'headerCardAction headerCardActionInMenu')
);

$this->headTitle($title);

echo $this->cardHeader($hc).PHP_EOL;

echo '<div class="forumPostList card noPaddingCard">'.PHP_EOL;
	echo $this->forumPostList($this->topic, $this->posts, $this->page, $this->lastLogin);
echo '</div>'.PHP_EOL;

if ($paginationControl) {
	echo '<div class="listNavigation card">'.PHP_EOL;
		echo renderPaginationControl($paginationControl, 'bottom').PHP_EOL;
		if (!$userCanPost) {
			echo $this->addNewDataLink($this->dataType, $this->topic->id);
		}
	echo '</div>'.PHP_EOL;
}

if ($userCanPost) {
	echo '<div class="listNavigation card postFormContainer">'.PHP_EOL;
		echo $this->form->render();
	echo '</div>'.PHP_EOL;
}


