<ul>
    <li><a href="<?php echo $this->baseUrl ?>/example/helper/">Helper d'action</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/context/">Contextes</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/calendar/">Calendrier jQuery</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/pagination/">Pagination</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/form/">Formulaires</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/jqueryform/">Formulaires avec JQuery</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/references/">Acceder aux tables que l'on reference</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/dependences/">Dependences entre tables</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/testinserts/">Insertions</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/testupdates/">Updates</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/testgetitems/">Items postés</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/test-bread-crumbs/">BreadCrumbs</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/translate/">Traduction</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/translate-fr/">Traduction fr</a></li>
    <li><a href="<?php echo $this->baseUrl ?>/example/translate-en/">Traduction en</a></li>
</ul>