<?php
if (!$this->pageCount || $this->pageCount == 1){
    return;
}

$previous = $this->translate('previousItem'); 
$goToPreviousPage = ucfirst($this->translate('goToPreviousPage'));
$next = $this->translate('nextItem'); 
$goToNextPage = ucfirst($this->translate('goToNextPage'));

// Previous page link
if (isset($this->previous)){
    echo '<a aria-label="'.$goToPreviousPage.'" href="'.$this->url(array(
        'name' => $this->name,
        'id' => $this->id,
        'page' => $this->previous)).'">&lt; '.$previous.'</a> | ';
} else {
    echo '<span class="disabled">&lt; '.$previous.'</span> | ';
}

// Numbered page links
foreach ($this->pagesInRange as $page){
  if ($page != $this->current){
    echo '<a aria-hidden="true" href="'.$this->url(array(
        'name' => $this->name,
        'id' => $this->id,
        'page' => $page)).'">'.$page.'</a> | ';
  } else {
      echo '<span class="current">'.$page.'</span> | ';
  }
}

// Next page link
if (isset($this->next)){
    echo '<a aria-label="'.$goToNextPage.'" href="'.$this->url(array(
        'name' => $this->name,
        'id' => $this->id,
        'page' => $this->next)).'">'.$next.' &gt; </a>';
} else {
    echo '<span class="disabled">'.$next.' &gt;</span>';
}
?>
