<?php
if (!$this->pageCount || $this->pageCount == 1){
    return;
}
?>

<!-- Previous page link -->
<?php
if (isset($this->previous)){
    echo '<a href="'.$this->url(array('dataType'=> $this->dataType, 'page' => $this->previous)).'">&lt; '. $this->translate('previousItem').'</a> | ';
} else {
    echo '<span class="disabled">&lt; '.$this->translate('previousItem').'</span> | ';
}
?>
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page){
  if ($page != $this->current){
    echo '<a href="'.$this->url(array('dataType'=> $this->dataType, 'page' => $page)).'">'.$page.'</a> | ';
  } else {
      echo '<span class="current">'.$page.'</span> | ';
  }
}
?>
<!-- Next page link -->
<?php
if (isset($this->next)){
    echo '<a href="'.$this->url(array('dataType'=> $this->dataType, 'page' => $this->next)).'">'. $this->translate('nextItem').' &gt; </a>';
} else {
    echo '<span class="disabled">'. $this->translate('nextItem').' &gt;</span>';
}?>
