<?php 
echo $this->doctype().PHP_EOL; ?>
<html lang="<?php echo $this->pageLang ?>">
<head>
<?php
echo $this->headMeta()->appendName('keywords', implode(' ', $this->keywords)).PHP_EOL;
echo $this->headTitle($this->baseTitle).PHP_EOL;
$this->prepareCss(APPLICATION_ENV == 'production');
echo $this->headLink().PHP_EOL;?>
<?php echo $this->headScript().PHP_EOL;?>
</head>
<body>
  <div id="contentWrapper">
    <div id="pageContent">
<?php echo $this->layout()->content.PHP_EOL; ?>
    </div>
  </div>
<?php
echo $this->jQuery().PHP_EOL;
echo $this->inlineScript().PHP_EOL;
?>
</body>
</html>