<?php echo $this->doctype().PHP_EOL; ?>
<html lang="<?php echo $this->pageLang ?>">
<head>
<?php
if(!empty($this->keywords)){
	$this->headMeta()->appendName('keywords', implode(', ', $this->keywords)).PHP_EOL;
}
echo $this->headMeta().PHP_EOL;
echo $this->openGraph()->render().PHP_EOL;
echo $this->headTitle($this->translate('appBaseTitle')).PHP_EOL;
$this->prepareCss()->main(APPLICATION_ENV == 'production');
echo $this->headLink().PHP_EOL;
?>
<link rel="shortcut icon" href="<?php echo $this->favicons['favicon.ico'] ?>" />
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->favicons['apple-touch-icon.png'] ?>" />
<link rel="icon" type="image/png" href="<?php echo $this->favicons['favicon-32x32.png'] ?>" sizes="32x32">
<link rel="icon" type="image/png" href="<?php echo $this->favicons['favicon-16x16.png'] ?>" sizes="16x16">
<link rel="mask-icon" href="<?php echo $this->favicons['safari-pinned-tab.svg'] ?>" color="#454f0a">
<meta name="msapplication-config" content="<?php echo $this->favicons['browserconfig.xml'] ?>">

<link rel="alternate" type="application/rss+xml" title="<?php echo $this->translate('publicrss') ?>" href="<?php echo Globals::getRouter()->assemble(array(), 'publicrss', true)?>" />

<?php
$headerHelper = new Lib_View_Helper_Header($this, $this->acl, $this->user);
$header = $headerHelper->header();
$wrapperClass = $headerHelper->getEmptyCategoryContentClass();
echo $this->headScript().PHP_EOL;?>
</head>
<body class="<?php echo $this->pageClass ?>">
<?php
echo $this->imageErrorHandler($this->cspNonce).PHP_EOL;
echo $header;

if ($this->wrapperIsCard) {
    $wrapperCardClass = " card";
    $firstContentCardClass = "";
    $secondaryContentCardClass = ""; 
} else {
    $wrapperCardClass = "";
    if ($this->separateFirstContentCardHeader) {
        $firstContentCardClass = "leftCardContainer";
    } else {
        $firstContentCardClass = "card leftCard"; 
    }
    $secondaryContentCardClass =  "rightCardContainer";
}
if($this->richTextContent) {
    $firstContentCardClass .= " richTextContent";
}
?>
	<div id="wrapper" <?php echo $wrapperClass ?>>
		<div id="contentWrapper" aria-labelledby="mainTitle" class="twoColumns <?php echo $wrapperCardClass ?>">
			<main id="firstContent" class="<?php  echo $firstContentCardClass ?>">
<?php echo $this->layout()->content.PHP_EOL; ?>
    		</main>
			<aside id="secondContent" class="<?php echo $secondaryContentCardClass ?>">
<?php
	if($this->isHomePage){
		echo $this->facebook_LikeBox(FACEBOOK_PAGE_URL, "card");
	}
	echo $this->renderAdditionalContentItems($this->user, $this->acl, $this->additionalContentItems, Content::COLUMN2).PHP_EOL;
?>
			</aside>
		</div>
<?php if($this->layout()->comments){?>
		<div id="comments">
<?php echo $this->layout()->comments . PHP_EOL; ?>
		</div>
<?php } ?>
  	</div>
<?php echo $this->includeView("commonviews/footer.phtml"); ?>
	<div id="overlay">
		<a class="close closeModal" id="closeModal" href="#"></a>
		<div id="modalContent" class="modalContent">
<?php echo $this->modalContentRenderer($this->modalContent).PHP_EOL; ?>			
<?php echo $this->layout()->modal . PHP_EOL; ?>
	 	</div>
	 	<div id="mobileMenu" class="mobileMenu offscreen">
	 		<?php echo $headerHelper->mobileMenu() ?>
	 	</div>
	 	<?php if ($this->searchFormMobile) { ?>
	 	<div id="mobileSearchContainer"><?php echo $this->searchFormMobile ?></div>
	 	<?php } ?>
 	</div>
<?php
$this->google_Analytics();
echo $this->jQuery().PHP_EOL;
echo $this->inlineScript().PHP_EOL;
?>
</body>
</html>
