<?php
echo $this->doctype().PHP_EOL; ?>
<html lang="<?php echo $this->pageLang ?>">
<head>
<?php
if(!empty($this->keywords)){
	$this->headMeta()->appendName('keywords', implode(', ', $this->keywords)).PHP_EOL;
}
echo $this->headMeta();
?>

<!--[if IE]><![endif]-->
<?php
echo $this->headTitle($this->translate('appBaseTitle')).PHP_EOL;
$this->prepareCss()->main(APPLICATION_ENV == 'production');
echo $this->headLink().PHP_EOL;
?>
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->prepareCss()->ieCss(APPLICATION_ENV == 'production') ?>" />
<![endif]-->
<link rel="shortcut icon" href="<?php echo $this->favicons['favicon.ico'] ?>" />
<link rel="apple-touch-icon" sizes="180x180" href="<?php echo $this->favicons['apple-touch-icon.png'] ?>" />
<link rel="icon" type="image/png" href="<?php echo $this->favicons['favicon-32x32.png'] ?>" sizes="32x32">
<link rel="icon" type="image/png" href="<?php echo $this->favicons['favicon-16x16.png'] ?>" sizes="16x16">
<link rel="mask-icon" href="<?php echo $this->favicons['safari-pinned-tab.svg'] ?>" color="#454f0a">
<meta name="theme-color" content="#ff0000">
<meta name="msapplication-config" content="<?php echo $this->favicons['browserconfig.xml'] ?>">

<link rel="alternate" type="application/rss+xml" title="<?php echo $this->translate('publicrss') ?>" href="<?php echo Globals::getRouter()->assemble(array(), 'publicrss', true)?>" />

<?php
$headerHelper = new Lib_View_Helper_Header($this, $this->acl, $this->user);
$header = $headerHelper->header();
$wrapperClass = $headerHelper->getEmptyCategoryContentClass();
echo $this->headScript().PHP_EOL;?>
</head>
<body>
<?php
echo $header;
?>
	<div id="wrapper" <?php echo $wrapperClass ?>>
		<div id="contentWrapper" aria-labelledby="mainTitle" class="twoColumns">
			<main id="firstContent"<?php if($this->richTextContent) echo ' class="richTextContent"'?>>
<?php echo $this->layout()->content.PHP_EOL; ?>
    		</main>
			<aside id="secondContent">
<?php
	echo $this->renderAdditionalContentItems($this->user, $this->acl, $this->additionalContentItems, Content::COLUMN2).PHP_EOL;
	if($this->isHomePage){
		echo $this->facebook_LikeBox(FACEBOOK_PAGE_URL);
	}
?>
			</aside>
		</div>
<?php if($this->layout()->comments){?>
		<div id="comments">
<?php echo $this->layout()->comments . PHP_EOL; ?>
		</div>
<?php } ?>
    	<div id="modalInfo">
			<a class="close" href="javascript:void(0);"></a>
			<div class="modalContent">
<?php echo $this->layout()->modal . PHP_EOL; ?>
			</div>
    	</div>
  	</div>
<?php echo $this->includeView("commonviews/footer.phtml"); ?>
	<div id="overlay"></div>
	<div id="menuOverlay"></div>
<?php
$this->google_Analytics();
$this->imageErrorHandler();
echo $this->jQuery().PHP_EOL;
echo $this->inlineScript().PHP_EOL;
?>
</body>
</html>
