<?php
	$subCategories = array(
		'forums' => 'forums',
		'photos' => 'photos',
		'videos' => 'videos',
		'france' => 'france',
		'users' => 'userlist',
		'spots' => 'listspots',
		'tricks' => 'listtricks',
		'blogs' => 'listblogs',
	);
?>
<h1 id="mainTitle" class="subCategoriesTitle"><?php echo ucfirst($this->translate('communitySubCategoriesTitle')) ?></h1>
<p class="subCategoriesDescription"><?php echo ucfirst($this->translate('communitySubCategoriesDescription')) ?></p>
<ul id="communitySubCategoriesDescription">
<?php foreach($subCategories as $k => $v){?>
	<li>
		<h2><div class="actionLinkContainer"><?php echo $this->routeLink($v, null, array(), '') ?></div></h2>
		<?php echo ucfirst($this->translate($k.'Description')) ?>
	</li>

<?php } ?>
</ul>
