<?php
$title = ucfirst($this->translate('search'));
$this->headTitle($title);
?>
<div class="card">
	<h1 id="mainTitle" class="pageTitle"><?php echo $title ?></h1>
	<div class=" search">
		<?php echo $this->form; ?>
	</div>
<?php
if(empty($this->searchTerms)){
	return;
} else {
	echo '	<div>'.sprintf(ucfirst($this->translate('searchResultsInfo')), $this->searchInfo['totalFound']).'</div>'.PHP_EOL;
}
if(count($this->items) > 0){
	echo '	<ul class="searchResults">';
	foreach ($this->items as $i => $item) {
	    echo "		<li>".$this->itemLink($item).' '.$item->getDate(false)."<br/>".$this->excerpts[$i]."</li>";
	}
	echo '	</ul>';
} else {
	echo '	<p>No results</p>';
}
echo '</div>';