<?php
$this->headTitle(ucfirst(sprintf($this->translate('newStuffFor'), $this->escape(Globals::getUser()->username))));
$this->keywords = array('home');
$showNewItems = ($this->items['newElementsAndMetadata']) || $this->newUnreadMessages;
$showOldItems = ($this->items['oldElementsAndNewMetadata']) || $this->oldUnreadMessages;

?>
<h1 id="mainTitle" class="pageTitle"><?php echo ucfirst($this->translate('newstuff'))?></h1>

<?php
echo '<div class="actionLinkContainer">'.ucfirst($this->translate('showStuffPosted')).' '.$this->rangeForm.'</div>'.PHP_EOL;
echo '<div class="actionLinkContainer">'.$this->routeLink('markallasread').'</div>'.PHP_EOL;
echo '<div class="actionLinkContainer">'.$this->routeLink('editnotifications').'</div>'.PHP_EOL;
?>
<div id='newItems'>
<?php
if($showNewItems){
	echo '<h2 class="itemSectionTitle">'.PHP_EOL;
	if(!$this->until){
		$range = $this->translate($this->range);
		echo sprintf(ucfirst($this->translate('notificationNewItemsSince')).' :', $range, $this->date($this->from, true));
	} else {
		echo sprintf(ucfirst($this->translate('notificationNewItemsFromUntil')).' :', $this->date($this->from, true), $this->date($this->until, true));
	}
	echo '</h2>'.PHP_EOL;
	echo $this->newItemsList($this->items['newElementsAndMetadata']);
	if($showNewItems && !empty($this->items['oldElementsAndNewMetadata'])){
		echo '<h2 class="itemSectionTitle">'.PHP_EOL;
		echo ucfirst($this->translate('notificationNewMetaDataAlso')).'...';
		echo '</h2>'.PHP_EOL;
	}
} else {
	if($showOldItems){
		echo '<h2 class="itemSectionTitle">'.PHP_EOL;
		echo ucfirst($this->translate('notificationNewMetaData')).'...';
		echo '</h2>'.PHP_EOL;
	}
}
if($this->items['oldElementsAndNewMetadata']){
	echo $this->newItemsList($this->items['oldElementsAndNewMetadata'], true);
}

if(empty($this->items['newElementsAndMetadata']) && empty($this->items['oldElementsAndNewMetadata'])){
	echo '<p class="noNewStuff">'.ucfirst($this->translate('noNewStuff')).'</p>'.PHP_EOL;
}
?>
</div>
<?php
if(empty($this->items['newElementsAndMetadata']) && empty($this->items['oldElementsAndNewMetadata'])){
	echo $this->userActionSuggestions($this->user, 'newStuff');
}




