<?php
$title = ucfirst($this->translate('newstuff'));
$this->headTitle(ucfirst(sprintf(
    $this->translate('newStuffFor'),
    $this->escape(Globals::getUser()->username))));
$showNewItems = (
    $this->items['newElementsAndMetadata']) || $this->newUnreadMessages;
$showOldItems = (
    $this->items['oldElementsAndNewMetadata']) || $this->oldUnreadMessages;    
    
$hc = new HeaderContent($title);
$hc->setHeaderActions(getPreferences($this), getMarkAsRead($this));

function getPreferences($view)
{
    $content = '<div class="headerCardAction headerCardActionInMenu actionLinkContainer">'.PHP_EOL;
    $content .= ucfirst($view->routeLink('editnotifications')).PHP_EOL;
    $content .= '</div>'.PHP_EOL;
    return $content;
}

function getNewStuff($view)
{
    $content = '<div class="actionLinkContainer">'.PHP_EOL;
    $content .= ucfirst($view->translate('showStuffPosted')).PHP_EOL;
    $content .= ' '.$view->rangeForm.'</div>'.PHP_EOL;
    return $content;
}

function getMarkAsRead($view)
{
    $content = '<div class="headerCardAction headerCardActionInMenu actionLinkContainer">'.PHP_EOL;
    $content .= ucfirst($view->routeLink('markallasread')).PHP_EOL;
    $content .= '</div>'.PHP_EOL;
    return $content;
}

echo $this->cardHeader($hc).PHP_EOL;
?>
<div class="card">
	<?php echo getNewStuff($this); ?>
</div>

<div class="card">
	<div id='newItems'>
<?php
if($showNewItems){
	echo '<h2 class="itemSectionTitle">'.PHP_EOL;
	if(!$this->until){
		$range = $this->translate($this->range);
		echo sprintf(ucfirst($this->translate('notificationNewItemsSince')).' :', $range, $this->date($this->from, true));
	} else {
		echo sprintf(ucfirst($this->translate('notificationNewItemsFromUntil')).' :', $this->date($this->from, true), $this->date($this->until, true));
	}
	echo '</h2>'.PHP_EOL;
	echo $this->newItemsList($this->items['newElementsAndMetadata']);
	if($showNewItems && !empty($this->items['oldElementsAndNewMetadata'])){
		echo '<h2 class="itemSectionTitle">'.PHP_EOL;
		echo ucfirst($this->translate('notificationNewMetaDataAlso')).'...';
		echo '</h2>'.PHP_EOL;
	}
} else {
	if($showOldItems){
		echo '<h2 class="itemSectionTitle">'.PHP_EOL;
		echo ucfirst($this->translate('notificationNewMetaData')).'...';
		echo '</h2>'.PHP_EOL;
	}
}
if($this->items['oldElementsAndNewMetadata']){
	echo $this->newItemsList($this->items['oldElementsAndNewMetadata'], true);
}

if(empty($this->items['newElementsAndMetadata']) && empty($this->items['oldElementsAndNewMetadata'])){
	echo '<p class="noNewStuff">'.ucfirst($this->translate('noNewStuff')).'</p>'.PHP_EOL;
}
?>
	</div>
<?php
if(empty($this->items['newElementsAndMetadata']) && empty($this->items['oldElementsAndNewMetadata'])){
	echo $this->userActionSuggestions($this->user, 'newStuff');
}
?>
</div>