<?php
/**
 * VARIABLES 
 */
$username = $this->escape($this->profilee->getTitle());
$isMyPage = ($this->profilee->{User::COLUMN_USERID} == $this->user->{User::COLUMN_USERID});
$isLoggedIn = $this->user->isLoggedIn();
$location = $this->profilee->getLocation();

/**
 * FUNCTIONS 
 */

function maybeUserPreferencesCard($isMyPage, $view)
{
    $content = "";
    if($isMyPage){
        $content .= '<div class="card">'.PHP_EOL;
    	$content .= '  <div id="userPreferences">'.PHP_EOL;
    	$content .= '	 <p class="actionLinkContainer">'.$view->routeLink('userupdate').'</p>'.PHP_EOL;
    	$content .= '	 <p class="actionLinkContainer">'.$view->routeLink('editnotifications').'</p>'.PHP_EOL;
    	$content .= '  </div>'.PHP_EOL;
    	$content .= '</div>'.PHP_EOL;
    }
    return $content;
}

function renderUserInfoItem($view, $title, $value, $escape = true)
{
    $value = trim($value);
    if (empty($value)) {
        return '';
    }
    $safeValue = $escape ? $view->escape($value) : $value;
    $content = "		<li>".PHP_EOL;
    $content .= "           ".ucfirst($view->translate($title)).": ".$safeValue.PHP_EOL;
    $content .= "       </li>".PHP_EOL;
    return $content;
}

function personalInformation($user, $isLoggedIn, $view)
{
    $content = '	<ul id="personalInformation">'.PHP_EOL;
    
    // LAST VISIT
    $lastLoggedin = $user->lastLogin ? $view->date($user->lastLogin, false) : null;
    if($isLoggedIn){
    	$content .= renderUserInfoItem($view, 'lastLoggedIn', $lastLoggedin);
    }
    
    // REAL NAME
    if($isLoggedIn){
        $content .= renderUserInfoItem($view, 'realName',
            ucfirst($user->firstName) . ' ' . ucfirst($user->lastName));
    }
    
    // GENDER
    $gender = (!empty($user->gender)) ? ucfirst($view->translate(Lib_Form_Element_Gender::$genders[$user->gender])) : '';
    if($gender && $isLoggedIn){
    	$content .= renderUserInfoItem($view, 'gender', $gender);
    }
    
    // DATE OF BIRTH
    $dob = (!empty($user->birthDate) && $user->birthDate != '0000-00-00') ? $view->date($user->birthDate, false) : null;
    if($dob && $isLoggedIn){
    	$content .= renderUserInfoItem($view, 'birthDate', $dob);
    }
    
    // LOCATION
    $where = $view->renderLocationInfo($user);
    if($where){
    	$content .= renderUserInfoItem($view, 'livesIn', $where, false);
    }
    
    // OCCUPATION
    if($isLoggedIn){
    	$content .= renderUserInfoItem($view, 'occupation', ucfirst($user->occupation));
    }
    
    $content .= '    	</ul>'.PHP_EOL;
    return $content;
}

function contactInformation($user, $isLoggedIn, $userBlog, $view)
{
    $content = '    	<ul id="contactInformation">'.PHP_EOL;
    
    $site = $view->escape($user->site);
    if(!empty($site)){
    	$content .= renderUserInfoItem($view, 'site', '<a rel="nofollow" href="'.$site.'">'.$site.'</a>', false);
    }
    
    $blogLink = $userBlog->hasBlogPosts() ? $view->itemLink($userBlog) : null;
    $content .= renderUserInfoItem($view, 'userBlog', $blogLink, false);
  	
    $content .= '    	</ul>'.PHP_EOL;
    return $content;
}

function rideInformation($user, $view)
{
    $content = '';
    $content .= '    	<ul id="rideInformation">'.PHP_EOL;
    
    $content .= renderUserInfoItem($view, 'rideType', $view->rideType($user), false);
    
    $level = $view->escape($user->level);
    if($level){
        $content .= renderUserInfoItem($view, 'level', $view->translate(Lib_Form_Element_Level::$levels[$level]), false);
    }

    $content .= renderUserInfoItem($view, 'gear', ucfirst($user->gear));
    
    $content .= renderUserInfoItem($view, 'otherSports', ucfirst($user->otherSports));

    $content .= "    	</ul>".PHP_EOL;
    return $content;
}

function maybeRenderLocationCard($isLoggedIn, $location, $view)
{
    if(!$isLoggedIn || !$location){
        return '';
    }
    
    $mapElementId = 'userMapElement';
    $view->googleMaps()->displayItem($location,
            array('mapElementId' => $mapElementId));
    $content = '<div class="card">'.PHP_EOL;
    $content .= '	<div class="userMap">'.PHP_EOL;
    $content .= '       <div id="'.$mapElementId.'" style="">'.PHP_EOL;
    $content .= '           <img src="'.$view->staticGoogleMap($location, 288, 288).'" alt="" />'.PHP_EOL;
    $content .= '       </div>'.PHP_EOL;
    $content .= '   </div>'.PHP_EOL;
    $content .= '</div>'.PHP_EOL;
    return $content;
}

function userNameCard($username)
{
    $content = '<div class="card">'.PHP_EOL;
    $content .= '	<h1 class="cardTitle">'.$username.'</h1>'.PHP_EOL;
    $content .= '</div>'.PHP_EOL;
    return $content;
}

function mainCard($userInfoCardContent, $userAlbumCardContent)
{
    $content =  '<div class="profilePageMainContainer">'.PHP_EOL;
    $content .= '   <div class="card profileInfoCard">'.PHP_EOL;
    $content .= $userInfoCardContent;
    $content .= '   </div>'.PHP_EOL;
    if ($userAlbumCardContent) {
        $content .= '   <div class="card profileAlbumCard">'.PHP_EOL;
        $content .= $userAlbumCardContent;
        $content .= '   </div>'.PHP_EOL;
    }
    $content .= '</div>'.PHP_EOL;
    return $content;
}

function userProfilePic($profilee, $isLoggedIn, $isMyPage, $view)
{
    $content = '<div id="userProfilePic">'.PHP_EOL;
    $content .= $view->profilePic($profilee).PHP_EOL;
    if($isLoggedIn && !$isMyPage){
    	$content .= '	<div class="profileMessageContainer actionLinkContainer">'.PHP_EOL;
    	$content .= '      '.$view->routeLink('privatemessagesnew', null,
    	    array('toUser' => $profilee->getTitle())).PHP_EOL;
    	$content .= '  </div>'.PHP_EOL;
    	if($this->user->status == User::STATUS_ADMIN){
    		$content .= '    <div class="actionLinkContainer">'.PHP_EOL;
    		$content .= '        '.$view->routeLink('impersonate', null,
    		    array('authCheck' => AUTHCHECK, 'i' => $view->profilee->getId())).PHP_EOL;
    		$content .= '    </div>'.PHP_EOL;
    	}
    }
    $content .= '</div>'.PHP_EOL;
    return $content;
}

function userAlbumCardContent($album, $view)
{
    return $view->albumPreview($album, 6);
}


/**
 * RENDERING 
 */
$userInfoCardContent = userProfilePic($this->profilee, $isLoggedIn, $isMyPage, $this);
$userInfoCardContent .= '<div class="userProfileInfo">'.PHP_EOL;
$userInfoCardContent .= personalInformation($this->profilee, $isLoggedIn, $this);
$userInfoCardContent .= contactInformation($this->profilee, $isLoggedIn, $this->blog, $this);
$userInfoCardContent .= rideInformation($this->profilee, $this);
$userInfoCardContent .= '</div>'.PHP_EOL;

echo userNameCard($username);
echo maybeUserPreferencesCard($isMyPage, $this);
echo mainCard($userInfoCardContent, userAlbumCardContent($this->album, $this));
echo maybeRenderLocationCard($isLoggedIn, $location, $this);
?>